# Generated by Django 6.0 on 2025-12-15 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('firewall', 'Firewall'), ('switch', 'Switch'), ('router', 'Router'), ('hypervisor', 'Hypervisor'), ('server', 'Server')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('prometheus_instance', models.CharField(help_text="Instance label in Prometheus (e.g., '10.10.1.254')", max_length=100)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_interface', models.CharField(help_text="e.g., 'ae0', 'ge-0/0/0'", max_length=50)),
                ('target_interface', models.CharField(max_length=50)),
                ('bandwidth_capacity', models.IntegerField(help_text='Capacity in Mbps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='api.device')),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='api.device')),
            ],
            options={
                'ordering': ['source_device', 'target_device'],
                'unique_together': {('source_device', 'source_interface', 'target_device', 'target_interface')},
            },
        ),
    ]
