# Generated by Django 6.0 on 2025-12-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_monitored',
            field=models.BooleanField(default=True, help_text='Whether this device has Prometheus metrics'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('firewall', 'Firewall'), ('switch', 'Switch'), ('router', 'Router'), ('hypervisor', 'Hypervisor'), ('server', 'Server'), ('isp', 'ISP Equipment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='prometheus_instance',
            field=models.CharField(blank=True, help_text='Instance label in Prometheus (leave blank for dummy nodes)', max_length=100),
        ),
    ]
