# Generated by Django 6.0 on 2025-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device_is_monitored_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='icon',
            field=models.TextField(blank=True, help_text='Base64 encoded image or emoji'),
        ),
    ]
