#!/bin/bash
set -e  # Exit on any error

echo "🗺️  NetMap Installation Script"
echo "================================"
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
   echo "❌ Please do not run as root. Run as a regular user with sudo access."
   exit 1
fi

# Get installation directory
INSTALL_DIR=$(pwd)
USER=$(whoami)

echo "📁 Installation directory: $INSTALL_DIR"
echo "👤 Installing for user: $USER"
echo ""

# Update system
echo "📦 Updating system packages..."
sudo apt update

# Install system dependencies
echo "📦 Installing system dependencies..."
sudo apt install -y python3 python3-pip python3-venv git

# Backend setup
echo "🐍 Setting up Python backend..."
cd $INSTALL_DIR/backend

if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

# Generate SECRET_KEY
echo "🔑 Generating Django secret key..."
SECRET_KEY=$(python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')

# Get configuration from user
CURRENT_IP=$(hostname -I | awk '{print $1}')
echo ""
echo "🌐 Detected IP address: $CURRENT_IP"
read -p "Enter your domain name (or press Enter to skip): " DOMAIN_NAME

# Prompt for Prometheus URL
echo ""
read -p "Enter Prometheus URL (default: http://localhost:9090): " PROM_URL
PROM_URL=${PROM_URL:-http://localhost:9090}

# Create settings_local.py
echo "⚙️  Creating local settings..."
cat > netmap/settings_local.py <<EOF
# Local settings - DO NOT COMMIT THIS FILE
# Generated by install.sh on $(date)

SECRET_KEY = '$SECRET_KEY'

# Add your server IP and domain
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '$CURRENT_IP'$([ -n "$DOMAIN_NAME" ] && echo ", '$DOMAIN_NAME'")]

# Update this to point to your Prometheus server
PROMETHEUS_URL = '$PROM_URL'

# Optional: Enable debug mode (disable in production)
# DEBUG = False
EOF

echo "✅ Created settings_local.py"

# Run migrations
echo "🔄 Running database migrations..."
python manage.py migrate

# Create superuser (interactive)
echo ""
echo "👤 Create Django admin user (optional)..."
read -p "Create admin user now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    python manage.py createsuperuser
fi

deactivate

# Create systemd service for Daphne (ASGI/WebSocket server)
echo "🔧 Creating systemd service for Daphne (WebSocket support)..."
sudo tee /etc/systemd/system/netmap.service > /dev/null <<EOF
[Unit]
Description=NetMap Network Topology Visualizer with WebSocket Support
After=network.target

[Service]
Type=simple
User=$USER
Group=$USER
WorkingDirectory=$INSTALL_DIR/backend
Environment="PATH=$INSTALL_DIR/backend/venv/bin"
ExecStart=$INSTALL_DIR/backend/venv/bin/daphne -b 0.0.0.0 -p 8000 netmap.asgi:application
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd and enable service
echo "🔄 Enabling and starting NetMap service..."
sudo systemctl daemon-reload
sudo systemctl enable netmap
sudo systemctl start netmap

# Wait a moment for service to start
sleep 2

# Check service status
echo ""
echo "✅ Installation complete!"
echo ""
echo "📊 Service Status:"
sudo systemctl status netmap --no-pager -l | head -n 10
echo ""
echo "🌐 NetMap is now running at:"
echo "   http://$CURRENT_IP:8000"
echo "   http://localhost:8000"
if [ -n "$DOMAIN_NAME" ]; then
    echo "   http://$DOMAIN_NAME:8000"
fi
echo ""
echo "⚡ Features enabled:"
echo "   ✓ Real-time WebSocket updates (no 30s polling!)"
echo "   ✓ Instant topology changes across all connected clients"
echo "   ✓ Live bandwidth monitoring"
echo "   ✓ Auto-reconnect on connection loss"
echo ""
echo "📝 Useful commands:"
echo "   sudo systemctl status netmap    - Check service status"
echo "   sudo systemctl restart netmap   - Restart service"
echo "   sudo systemctl stop netmap      - Stop service"
echo "   sudo journalctl -u netmap -f    - View logs"
echo ""
echo "🔐 Django admin available at:"
echo "   http://$CURRENT_IP:8000/admin"
echo ""
echo "⚙️  Configuration:"
echo "   Settings file: $INSTALL_DIR/backend/netmap/settings_local.py"
echo "   Edit this file to update Prometheus URL or add domains"
echo ""
echo "📚 Next steps:"
echo "   1. Set up Prometheus with SNMP Exporter"
echo "   2. Add your devices via the web interface"
echo "   3. Configure network monitoring targets"
echo "   4. (Optional) Set up Nginx reverse proxy with SSL for WebSocket support"
echo ""
echo "💡 Note: If using Nginx, ensure your config includes WebSocket proxy headers:"
echo "   proxy_http_version 1.1;"
echo "   proxy_set_header Upgrade \$http_upgrade;"
echo "   proxy_set_header Connection \"upgrade\";"
echo ""
